POST https://node-postgres-fastify.onrender.com/videos
Content-Type: application/json

{
  "title":"Video node Exemplo 4",
  "description": "Esse é o primeiro video",
  "duration": "180"
}

###
Get https://node-postgres-fastify.onrender.com/videos


###
PUT https://node-postgres-fastify.onrender.com/videos/
Content-Type: application/json

{
  "title":"Video 02 alterado",
  "description": "Esse é SEGUNDO video",
  "duration": "10"
}

###
DELETE   https://node-postgres-fastify.onrender.com/videos/70f978c0-1b06-4966-8bc0-097745808dbf
